import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readConfig } from "./config.js";
import { scanAll } from "./scanners/index.js";
import { checkGuideFreshness } from "./checker.js";

/**
 * Regenerate snapshot.md and rebuild index.yaml from current project artifacts.
 */
export function refresh() {
  const projectRoot = process.cwd();

  console.log("\n  knowledge-system refresh\n");

  if (!existsSync(join(projectRoot, ".knowledge"))) {
    console.error("  Error: .knowledge/ not found. Run 'knowledge-system init' first.");
    process.exit(1);
  }

  const config = readConfig(projectRoot);
  if (!config) {
    console.error("  Error: .knowledge/config.yaml not found or unreadable.");
    process.exit(1);
  }

  // Scan all artifact sources
  console.log("  Scanning artifacts...");
  const artifacts = scanAll(projectRoot, config);

  console.log(`    guides:       ${artifacts.guides.length}`);
  console.log(`    conventions:  ${artifacts.conventions.length}`);
  console.log(`    adrs:         ${artifacts.adrs.length}`);
  console.log(`    features:     ${artifacts.features.length}`);

  // Check freshness for each guide
  for (const guide of artifacts.guides) {
    const result = checkGuideFreshness(guide, projectRoot);
    guide.status = result.status;
  }

  // Build index.yaml
  console.log("  Building index...");
  const index = buildIndex(artifacts);
  const indexPath = join(projectRoot, ".knowledge", "index.yaml");
  writeFileSync(indexPath, index);
  console.log("    write .knowledge/index.yaml");

  // Build snapshot.md
  console.log("  Building snapshot...");
  const snapshot = buildSnapshot(artifacts, config);
  const snapshotPath = join(projectRoot, ".knowledge", "snapshot.md");
  writeFileSync(snapshotPath, snapshot);
  console.log("    write .knowledge/snapshot.md");

  console.log();
  console.log("  Done! Index and snapshot refreshed.\n");
}

function buildIndex(artifacts) {
  const lines = [];
  lines.push(`version: "1.0"`);
  lines.push(`generated: "${new Date().toISOString()}"`);
  lines.push("");

  // Guides
  lines.push("guides:");
  if (artifacts.guides.length === 0) {
    lines.push("  []");
  } else {
    for (const g of artifacts.guides) {
      lines.push(`  - id: ${g.id}`);
      lines.push(`    title: "${escYaml(g.title)}"`);
      lines.push(`    path: ${g.path}`);
      lines.push(`    summary: "${escYaml(g.summary)}"`);
      lines.push(`    topics: [${g.topics.join(", ")}]`);
      lines.push(`    status: ${g.status}`);
    }
  }
  lines.push("");

  // Conventions
  lines.push("conventions:");
  if (artifacts.conventions.length === 0) {
    lines.push("  []");
  } else {
    for (const c of artifacts.conventions) {
      lines.push(`  - id: ${c.id}`);
      lines.push(`    title: "${escYaml(c.title)}"`);
      lines.push(`    path: ${c.path}`);
      lines.push(`    summary: "${escYaml(c.summary)}"`);
      lines.push(`    topics: [${c.topics.join(", ")}]`);
    }
  }
  lines.push("");

  // ADRs
  lines.push("adrs:");
  if (artifacts.adrs.length === 0) {
    lines.push("  []");
  } else {
    for (const a of artifacts.adrs) {
      lines.push(`  - id: ${a.id}`);
      lines.push(`    title: "${escYaml(a.title)}"`);
      lines.push(`    path: ${a.path}`);
      lines.push(`    summary: "${escYaml(a.summary)}"`);
      lines.push(`    topics: [${a.topics.join(", ")}]`);
      lines.push(`    status: ${a.status}`);
    }
  }
  lines.push("");

  // Features
  lines.push("features:");
  if (artifacts.features.length === 0) {
    lines.push("  []");
  } else {
    for (const f of artifacts.features) {
      lines.push(`  - id: ${f.id}`);
      lines.push(`    title: "${escYaml(f.title)}"`);
      lines.push(`    path: ${f.path}`);
      lines.push(`    stage: ${f.status}`);
      lines.push(`    topics: [${f.topics.join(", ")}]`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

function buildSnapshot(artifacts, config) {
  const lines = [];
  const timestamp = new Date().toISOString();

  lines.push("# Project Snapshot");
  lines.push("");
  lines.push("> Auto-generated by knowledge-system refresh. Do not edit.");
  lines.push(`> Generated: ${timestamp}`);
  lines.push("");

  // Active Conventions
  if (config.include_conventions && artifacts.conventions.length > 0) {
    lines.push("## Active Conventions");
    lines.push("");
    lines.push("| ID | Title |");
    lines.push("|----|-------|");
    for (const c of artifacts.conventions) {
      lines.push(`| ${c.id} | ${c.title} |`);
    }
    lines.push("");
  }

  // Architecture Decisions
  if (config.include_adrs && artifacts.adrs.length > 0) {
    lines.push("## Architecture Decisions");
    lines.push("");
    lines.push("| ID | Title | Status |");
    lines.push("|----|-------|--------|");
    for (const a of artifacts.adrs) {
      lines.push(`| ${a.id} | ${a.title} | ${a.status} |`);
    }
    lines.push("");
  }

  // Feature Dashboard
  if (config.include_features && artifacts.features.length > 0) {
    lines.push("## Feature Dashboard");
    lines.push("");
    lines.push("| ID | Title | Stage |");
    lines.push("|----|-------|-------|");
    for (const f of artifacts.features) {
      lines.push(`| ${f.id} | ${f.title} | ${f.status} |`);
    }
    lines.push("");
  }

  // Knowledge Guides
  if (artifacts.guides.length > 0) {
    lines.push("## Knowledge Guides");
    lines.push("");
    lines.push("| ID | Title | Status |");
    lines.push("|----|-------|--------|");
    for (const g of artifacts.guides) {
      lines.push(`| ${g.id} | ${g.title} | ${g.status} |`);
    }
    lines.push("");
  }

  // Technology Stack
  if (config.include_tech_stack) {
    lines.push("## Technology Stack");
    lines.push("");
    lines.push("- **Runtime**: Node.js >= 18.0.0 (ESM)");
    lines.push("- **Dependencies**: Zero runtime dependencies");
    lines.push("- **Package Manager**: npm workspaces");
    lines.push("- **Repository**: Git submodule monorepo");
    lines.push("");
  }

  return lines.join("\n");
}

function escYaml(str) {
  if (!str) return "";
  return str.replace(/"/g, '\\"');
}
